// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uadbfrmcnwrhnnlbwkfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhZGJmcm1jbndyaG5ubGJ3a2Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMTQ0NzUsImV4cCI6MjA2NzY5MDQ3NX0.LVz7j7CWEeUxlZhJ4YsZvSjlSvV0E8-xo7AXRaCOXwE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});